import Head from 'next/head'
import Link from 'next/link'

export default function Contact() {
    return (
        <div>
          <Head>
            <title>PLH Photography</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <main>
            <h1>
              Contact Page
            </h1>  
            <Link href="/"> 
              <a>back to home</a>
            </Link>       
          </main>
        </div>
      )
  }