import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>PLH Photography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Paul Le Houillier&apos;s Website
        </h1>  
        <Link href="/contact"> 
          <a>contact</a>
        </Link>       
      </main>
    </div>
  )
}
